CREATE PROCEDURE USP_ST_CARGA_EMPRESAS

AS

-----------------------------
-- VERIFICA SE SCHEMA EXISTE
-----------------------------

IF OBJECT_ID('PBS_PROCFIT_ST.DBO.ST_EMPRESAS') IS NULL

BEGIN

	CREATE TABLE PBS_PROCFIT_ST.DBO.ST_EMPRESAS
	 (
	   COD_EMPRESA   NUMERIC(15)
	 , NOME          VARCHAR(100)
	 , NOME_FANTASIA VARCHAR(60)
	 )
	
END

---------------
-- LIMPA STAGE
---------------

TRUNCATE TABLE PBS_PROCFIT_ST.DBO.ST_EMPRESAS


---------------------
-- POPULA STAGE AREA
---------------------

INSERT INTO PBS_PROCFIT_ST.DBO.ST_EMPRESAS

SELECT EMPRESA_USUARIA
     , NOME
	 , NOME_FANTASIA
  FROM PBS_PROCFIT_DADOS.DBO.EMPRESAS_USUARIAS