CREATE PROCEDURE USP_ST_CARGA_CLIENTES

AS

-----------------------------
-- VERIFICA SE SCHEMA EXISTE
-----------------------------

IF OBJECT_ID('PBS_PROCFIT_ST.DBO.ST_CLIENTES') IS NULL

BEGIN

	CREATE TABLE PBS_PROCFIT_ST.DBO.ST_CLIENTES
	 (
	   COD_CLIENTE       NUMERIC(15)
	 , NOME              VARCHAR(100)
	 , NOME_FANTASIA     VARCHAR(60)
	 , COD_CLASSIFICACAO NUMERIC(15)
	
	 )
	
END

IF OBJECT_ID('PBS_PROCFIT_ST.DBO.ST_CLASSIFICACOES') IS NULL

BEGIN

	CREATE TABLE PBS_PROCFIT_ST.DBO.ST_CLASSIFICACOES
	 (
	   COD_CLASSIFICACAO_CLIENTE NUMERIC(15)
	 , DESCRICAO VARCHAR(80)
	
	 )

END

IF OBJECT_ID('PBS_PROCFIT_ST.DBO.ST_CLIENTES_ENDERECOS') IS NULL

BEGIN

	CREATE TABLE PBS_PROCFIT_ST.DBO.ST_CLIENTES_ENDERECOS
	 (
	   ENTIDADE NUMERIC(15)
	 , CIDADE   VARCHAR(100)
	 , UF       CHAR(2)
	
	 )

END

IF OBJECT_ID('PBS_PROCFIT_ST.DBO.ST_CLIENTES_ESTADOS') IS NULL

BEGIN

	CREATE TABLE PBS_PROCFIT_ST.DBO.ST_CLIENTES_ESTADOS
	 (
	   UF     CHAR(2)
	 , ESTADO VARCHAR(60)
	 )

END

---------------
-- LIMPA STAGE
---------------

TRUNCATE TABLE PBS_PROCFIT_ST.DBO.ST_CLIENTES

TRUNCATE TABLE PBS_PROCFIT_ST.DBO.ST_CLASSIFICACOES

TRUNCATE TABLE PBS_PROCFIT_ST.DBO.ST_CLIENTES_ENDERECOS

TRUNCATE TABLE PBS_PROCFIT_ST.DBO.ST_CLIENTES_ESTADOS

---------------------
-- POPULA STAGE AREA
---------------------

INSERT INTO PBS_PROCFIT_ST.DBO.ST_CLIENTES

SELECT ENTIDADE
        , NOME
		, NOME_FANTASIA
		, CLASSIFICACAO_CLIENTE
  FROM PBS_PROCFIT_DADOS.DBO.ENTIDADES

INSERT INTO PBS_PROCFIT_ST.DBO.ST_CLASSIFICACOES

SELECT CLASSIFICACAO_CLIENTE
     , DESCRICAO
  FROM PBS_PROCFIT_DADOS.DBO.CLASSIFICACOES_CLIENTES

INSERT INTO PBS_PROCFIT_ST.DBO.ST_CLIENTES_ENDERECOS

SELECT ENTIDADE
     , CIDADE
     , ESTADO
  FROM PBS_PROCFIT_DADOS.DBO.ENDERECOS

INSERT INTO PBS_PROCFIT_ST.DBO.ST_CLIENTES_ESTADOS

SELECT ESTADO
     , NOME
  FROM PBS_PROCFIT_DADOS.DBO.ESTADOS