CREATE PROCEDURE USP_ST_CARGA_VENDEDORES

AS

-----------------------------
-- VERIFICA SE SCHEMA EXISTE
-----------------------------

IF OBJECT_ID('PBS_PROCFIT_ST.DBO.ST_VENDEDORES') IS NULL

BEGIN

	CREATE TABLE PBS_PROCFIT_ST.DBO.ST_VENDEDORES
	 (
	   COD_VENDEDOR NUMERIC(15)
	 , NOME         VARCHAR(100)
	 )
	
END

---------------
-- LIMPA STAGE
---------------

TRUNCATE TABLE PBS_PROCFIT_ST.DBO.ST_VENDEDORES


---------------------
-- POPULA STAGE AREA
---------------------

INSERT INTO PBS_PROCFIT_ST.DBO.ST_VENDEDORES

SELECT VENDEDOR
     , NOME
  FROM PBS_PROCFIT_DADOS.DBO.VENDEDORES