CREATE PROCEDURE USP_FULL_D_VENDEDORES

AS

-----------------------------
-- VERIFICA SE SCHEMA EXISTE
-----------------------------

IF OBJECT_ID('PBS_PROCFIT_DW.DBO.D_VENDEDORES') IS NULL
BEGIN
	CREATE TABLE D_VENDEDORES
	(
	  COD_VENDEDOR NUMERIC(15) PRIMARY KEY 
	, NOME VARCHAR(160)
	)
END


----------------
-- FAZENDO MERGE
----------------

MERGE PBS_PROCFIT_DW.DBO.D_VENDEDORES D
USING PBS_PROCFIT_ST.DBO.VW_D_VENDEDORES O ON D.COD_VENDEDOR = O.COD_VENDEDOR

-- QUANDO COINCIDIR
WHEN MATCHED THEN UPDATE
SET NOME = O.NOME

-- QUANDO NÃO COINCIDIR NO DESTINO
WHEN NOT MATCHED BY TARGET THEN INSERT
( COD_VENDEDOR
, NOME
)

VALUES
( O.COD_VENDEDOR
, O.NOME
);