CREATE PROCEDURE USP_ST_CARGA_VENDAS ( @INCRIMENTAL BIT )

/*
@INCRIMENTAL = 0 --CARGA FULL
@INCRIMENTAL = 1 --CARGA INCRIMENTAL
*/

AS

-----------------------------
-- VERIFICA SE SCHEMA EXISTE
-----------------------------

IF OBJECT_ID('PBS_PROCFIT_ST.DBO.ST_VENDAS') IS NULL

BEGIN

	CREATE TABLE PBS_PROCFIT_ST.DBO.ST_VENDAS
	 (
	   N_DOC          NUMERIC(15)
     , COD_EMPRESA    NUMERIC(15)
	 , COD_CLIENTE    NUMERIC(15)
	 , COD_VENDEDOR   NUMERIC(15)
	 , MOVIMENTO      DATE
     , COD_PRODUTO    NUMERIC(15)
	 , QUANTIDADE     INT
	 , VENDA_BRUTA    MONEY
	 , DESCONTO_TOTAL MONEY
	 , VENDA_LIQUIDA  MONEY
	 )
	
END

---------------
-- LIMPA STAGE
---------------

TRUNCATE TABLE PBS_PROCFIT_ST.DBO.ST_VENDAS


---------------------
-- POPULA STAGE AREA
---------------------

INSERT INTO PBS_PROCFIT_ST.DBO.ST_VENDAS

SELECT DOCUMENTO_NUMERO
     , EMPRESA
	 , CLIENTE
	 , VENDEDOR
	 , MOVIMENTO
     , PRODUTO
	 , QUANTIDADE
	 , VENDA_BRUTA
	 , DESCONTO + DESCONTO_NEGOCIADO AS DESCONTO
	 , VENDA_LIQUIDA
  FROM PBS_PROCFIT_DADOS.DBO.VENDAS_ANALITICAS
 WHERE MOVIMENTO > CASE WHEN @INCRIMENTAL = 1 THEN ( SELECT MAX(MOVIMENTO) FROM PBS_PROCFIT_DW.DBO.F_VENDAS )
						ELSE '01/01/1900'
					END