CREATE PROCEDURE USP_FULL_D_EMPRESAS

AS

-----------------------------
-- VERIFICA SE SCHEMA EXISTE
-----------------------------

IF OBJECT_ID('PBS_PROCFIT_DW.DBO.D_EMPRESAS') IS NULL
BEGIN
	CREATE TABLE D_EMPRESAS
	(
	  COD_EMPRESA NUMERIC(15) PRIMARY KEY 
	, NOME VARCHAR(160)
	, NOME_FANTASIA VARCHAR(80)
	)
END

----------------
-- FAZENDO MERGE
----------------

MERGE PBS_PROCFIT_DW.DBO.D_EMPRESAS D
USING PBS_PROCFIT_ST.DBO.VW_D_EMPRESAS O ON D.COD_EMPRESA = O.COD_EMPRESA

-- QUANDO COINCIDIR
WHEN MATCHED THEN UPDATE
SET NOME          = O.NOME           
  , NOME_FANTASIA = O.NOME_FANTASIA

-- QUANDO NÃO COINCIDIR NO DESTINO
WHEN NOT MATCHED BY TARGET THEN INSERT
( COD_EMPRESA
, NOME         
, NOME_FANTASIA
)

VALUES
( O.COD_EMPRESA
, O.NOME         
, O.NOME_FANTASIA
);
