CREATE VIEW VW_D_CLIENTES

AS
   SELECT 0 AS COD_CLIENTE
        , 'Não informado' AS NOME
		, 'Não informado' AS NOME_FANTASIA
		, 'Não informado' AS CLASSIFICACAO_CLIENTE
		, 'Não informado' AS CIDADE
		, 'Não informado' AS ESTADO
		, 'ND'            AS UF

UNION ALL

   SELECT A.COD_CLIENTE
        , A.NOME
		, A.NOME_FANTASIA
		, COALESCE(DBO.FN_CAMEL_CASE(B.DESCRICAO), 'Não Informado') AS CLASSIFICACAO_CLIENTE
		, COALESCE(DBO.FN_CAMEL_CASE(C.CIDADE),    'Não Informado') AS CIDADE
		, COALESCE(DBO.FN_CAMEL_CASE(D.ESTADO),    'Não Informado') AS ESTADO
		, COALESCE(C.UF,        'ND'                              ) AS UF
     FROM ST_CLIENTES           A
LEFT JOIN ST_CLASSIFICACOES     B ON A.COD_CLASSIFICACAO = B.COD_CLASSIFICACAO_CLIENTE
LEFT JOIN ST_CLIENTES_ENDERECOS C ON A.COD_CLIENTE       = C.ENTIDADE
LEFT JOIN ST_CLIENTES_ESTADOS   D ON C.UF                = D.UF

CREATE VIEW VW_D_EMPRESAS

AS

SELECT 0 AS COD_EMPRESA
     , 'Não informado' AS NOME
	 , 'Não informado' AS NOME_FANTASIA

UNION ALL

SELECT COD_EMPRESA
     , DBO.FN_CAMEL_CASE( NOME )          AS NOME
	 , DBO.FN_CAMEL_CASE( NOME_FANTASIA ) AS NOME_FANTASIA
  FROM ST_EMPRESAS

CREATE VIEW VW_D_PRODUTOS

AS

SELECT 0 AS COD_PRODUTO
     , 'Não informado' AS DESCRICAO         
     , 'Não informado' AS DESCRICAO_REDUZIDA
     , 'Não informado' AS FAMILIA		   
     , 'Não informado' AS SECAO			   
     , 'Não informado' AS GRUPO			   
     , 'Não informado' AS SUB_GRUPO		   
     , 'Não informado' AS MARCA			   

UNION ALL

SELECT COD_PRODUTO
     , DBO.FN_CAMEL_CASE(DESCRICAO          ) AS DESCRICAO         
     , DBO.FN_CAMEL_CASE(DESCRICAO_REDUZIDA ) AS DESCRICAO_REDUZIDA
     , COALESCE(DBO.FN_CAMEL_CASE(FAMILIA), 'Não Informado') AS FAMILIA		   
     , DBO.FN_CAMEL_CASE(SECAO			    ) AS SECAO			   
     , DBO.FN_CAMEL_CASE(GRUPO			    ) AS GRUPO			   
     , DBO.FN_CAMEL_CASE(SUB_GRUPO		    ) AS SUB_GRUPO		   
     , DBO.FN_CAMEL_CASE(MARCA			    ) AS MARCA			   
  FROM ST_PRODUTOS


CREATE VIEW VW_D_VENDEDORES

AS

SELECT 0 AS COD_VENDEDOR
     , 'Não informado' AS NOME

UNION ALL

SELECT COD_VENDEDOR
     , DBO.FN_CAMEL_CASE(NOME) AS NOME
  FROM ST_VENDEDORES


CREATE VIEW VW_F_VENDAS

AS

SELECT COALESCE( N_DOC ,       0 ) AS N_DOC 
     , COALESCE( COD_EMPRESA,  0 ) AS COD_EMPRESA
     , COALESCE( COD_CLIENTE,  0 ) AS COD_CLIENTE
     , COALESCE( COD_VENDEDOR, 0 ) AS COD_VENDEDOR
     , MOVIMENTO
     , COALESCE( COD_PRODUTO,  0 ) AS COD_PRODUTO
     , QUANTIDADE
     , VENDA_BRUTA
     , DESCONTO_TOTAL
     , VENDA_LIQUIDA
  FROM ST_VENDAS