
USE CURSO_SQL 

DROP TABLE CLIENTES

CREATE TABLE 
	CLIENTES(
		ID_CLIENTE		INT			NOT NULL PRIMARY KEY IDENTITY(1,1),
		NOME			VARCHAR(60)	NOT NULL,
		TIPO_ENDERECO	VARCHAR(20)	NOT NULL,
		ENDERECO		VARCHAR(60) NOT NULL,
		NUMERO			NUMERIC(5)	NOT NULL,
		BAIRRO			VARCHAR(60) NOT NULL,
		COMPLEMENTO		VARCHAR(80)	NULL,
		CEP				CHAR(8)		NOT NULL
	)

CREATE TABLE 
	CLIENTES_TELEFONES(
		ID_CLIENTE	INT REFERENCES CLIENTES (ID_CLIENTE),
		DDD			NUMERIC(2),
		TELEFONE	NUMERIC(9),
		PRIMARY KEY(ID_CLIENTE, DDD, TELEFONE)
	)
