/*
ATALHO -> CTRL + R = EXIBE/OCULTA GRID RESULTADOS
*/

USE PBS_PROCFIT_DADOS

SELECT  emp.EMPRESA_USUARIA AS	EMPRESA,
		emp.NOME			AS	NOME_EMPRESA
	FROM EMPRESAS_USUARIAS emp

SELECT	e.ENTIDADE				AS	COD_CLIENTE,
		e.NOME					AS	NOME,
		e.INSCRICAO_FEDERAL		AS	CPF_CNPJ,
		e.ATIVO					AS	CADASTRO_ATIVO
		FROM ENTIDADES e