
SP_HELP NF_FATURAMENTO_PRODUTOS
/*
	OPERADORES DE CONCATENAÇÃO

	1.FORMA -> '+' (NÃO NÚMERICOS)

	SELECT 'JOÃO' + ' DA SILVA'
	SELECT '1' + '2'

	2.FORMA -> 'CONCAT' 

	SELECT CONCAT('JOÃO', ' DA SILVA')
	SELECT CONCAT('1', '2')
*/

SELECT	ENDERECO,
		CIDADE,
		ESTADO,
		CIDADE + ' - ' + ESTADO AS JUNCAO
	FROM ENDERECOS

SELECT	ENDERECO,
		CIDADE,
		ESTADO,
		CONCAT(CIDADE, ' - ', ESTADO) AS CONCATENACAO
	FROM ENDERECOS as END2
