-- LIKE -> OPERADOR DE FILTRO DE CAMPOS VARCHAR (TEXTO)
-- ( % ) -> IDEPENDENTE DO QUE VENHA
-- ( _ ) SUBSTITUIÇÃO

SELECT CIDADE
  FROM ENDERECOS
 WHERE CIDADE LIKE 'SAO PAULO'


SELECT CIDADE
  FROM ENDERECOS
 WHERE CIDADE LIKE '%ES'

SELECT CIDADE
  FROM ENDERECOS
 WHERE CIDADE LIKE 'SAO%'

 SELECT CIDADE
  FROM ENDERECOS
 WHERE CIDADE LIKE '%SA%'

 SELECT CIDADE
  FROM ENDERECOS
 WHERE CIDADE LIKE 'FO_TALEZA'

SELECT CIDADE
  FROM ENDERECOS
 WHERE CIDADE NOT LIKE 'SAO%'
