-- AND (e) -> TODAS AS CONDIÇÕES DEVERÂO SER OBEDECIDAS
-- OR (ou) -> AO MENOS UMA CONDIÇÕES DEVERÁ SER OBEDECIDA

SELECT *
  FROM ENTIDADES
 WHERE EMPRESA_NACIONAL = 'S'
   AND DATA_CADASTRO >= '2020/06/18'
   AND INSCRICAO_ESTADUAL NOT LIKE '%0001%'

SELECT *
  FROM ENTIDADES
 WHERE EMPRESA_NACIONAL = 'S'
    OR DATA_CADASTRO >= '2020/06/18'
    OR INSCRICAO_ESTADUAL NOT LIKE '%0001%'