-- IN() -> dentro lista
-- NOT IN() -> fora da lista

SELECT *
  FROM ENTIDADES
 WHERE ENTIDADE IN(1001, 1, 1035, 1258, 1455, 1254)

SELECT CIDADE, ESTADO
  FROM ENDERECOS
 WHERE ESTADO NOT IN('CE', 'SP', 'BA')