/*
NULL -> TOTALMENTE AUSENTE DE INFORMAÇÃO
NULL <> '' (VAZIO)

FUNÇÕES
COALESCE -> PADRÃO ANSI 
ISNULL
NULLIF

OPERADORES
IS NULL
NOT IS NULL
*/

SELECT MUNICIPIO,
	   CIDADE,
	   ESTADO,
	   ISNULL(COMPLEMENTO, 'SEM VALOR') AS COMPLEMENTO
  FROM ENDERECOS
 WHERE ISNULL(COMPLEMENTO, 'SEM VALOR') = 'SEM VALOR'
 ORDER
    BY COMPLEMENTO

SELECT MUNICIPIO,
	   CIDADE,
	   ESTADO,
	   COALESCE(COMPLEMENTO, 'SEM VALOR') AS COMPLEMENTO
  FROM ENDERECOS
 ORDER
    BY COMPLEMENTO

SELECT MUNICIPIO,
	   CIDADE,
	   ESTADO,
	   COALESCE(COMPLEMENTO, 'NULO') AS COMPLEMENTO
  FROM ENDERECOS
 WHERE COMPLEMENTO IS NULL
 ORDER
    BY COMPLEMENTO

SELECT MUNICIPIO,
	   CIDADE,
	   ESTADO,
	   NULLIF(COMPLEMENTO, NULL) AS COMPLEMENTO
  FROM ENDERECOS
 WHERE NULLIF(COMPLEMENTO, NULL) IS NULL
 ORDER
    BY COMPLEMENTO