/*
CEILING() -> ARREDONDA VALORES PARA BAIXO
FLOOR() -> ARREDONDA VALORES PARA CIMA
ROUND() -> ARREDONDA VALORES DE ACORDO COM CRITÉRIOS MATEMÁTICOS
ABS() -> RETORNA VALOR ABSOLUTO

*/

SELECT	TOP 100
		PRODUTO,
		QUANTIDADE,
		VENDA_BRUTA,
		CEILING(VENDA_BRUTA) AS FUNCAO_CEILING,
		FLOOR(VENDA_BRUTA)  AS FUNCAO_FLOOR,
		ROUND(VENDA_BRUTA, 0) AS FUNCAO_ROUND_0,
		ROUND(VENDA_BRUTA, 2) AS FUNCAO_ROUND_2,
		ABS(VENDA_BRUTA) AS FUNCAO_ABS
  FROM VENDAS_ANALITICAS
 WHERE ABS(CEILING(VENDA_BRUTA)) = 360