/*

--YEAR
--MONTH
--DAY

--DATEPART

	YEAR
	QUARTER
	MONTH
	DAYOFYEAR
	DAY
	WEEK
	WEEKDAY
	HOUR
	MINUTE
	SECOND

--DATEADD
--DATEDIFF
--EOMONTH
*/

SELECT	GETDATE() AS DATA_HORA_ATUAL,
		YEAR( GETDATE()) AS ANO_ATUAL,
		MONTH( GETDATE()) AS MES_ATUAL,
		DAY( GETDATE()) AS DIA_ATUAL,
		DATEPART(HOUR, GETDATE()) AS HORA_ATUAL,
		DATEPART(MINUTE, GETDATE()) AS MINUTO_ATUAL,
		DATEPART(SECOND, GETDATE()) AS SEGUNDO_ATUAL,
		YEAR(DATEADD(YEAR, 1, GETDATE())) AS ANO_QUE_VEM,
		MONTH(DATEADD(MONTH, 1, GETDATE())) AS MES_QUE_VEM,
		DAY(DATEADD(DAY, 1, GETDATE())) AS DIA_QUE_VEM

SELECT	NOME,
		DATA_CADASTRO,
		YEAR(DATA_CADASTRO) AS ANO, -- DATEPART( YEAR, DATA_CADASTRO)
		MONTH(DATA_CADASTRO) AS MES,
		DAY(DATA_CADASTRO) AS DIA,
		DATEPART(QUARTER, DATA_CADASTRO) AS TRIMESTRE,
		DATEPART(WEEKDAY, DATA_CADASTRO) AS DIA_SEMANA,
		DATEPART(DAYOFYEAR, DATA_CADASTRO) AS DIA_ANO
  FROM ENTIDADES
 WHERE	DATEPART(QUARTER, DATA_CADASTRO) = 4
 ORDER
    BY ANO

SELECT	TITULO,
		MOVIMENTO,
		VENCIMENTO,
		DATEDIFF(DAY, MOVIMENTO, VENCIMENTO) AS PRAZO,
		EOMONTH(MOVIMENTO, 0) AS ULTIMA_DATA_MES,
		DATEADD(DAY, 1, EOMONTH(MOVIMENTO, -1)) AS PRIMEIRA_DATA_MES
  FROM	TITULOS_RECEBER