
-- FUNÇÕES DE AGREGAÇÃO

/*

SUM -> SOMA
MIN -> MÍNIMO
MAX -> MÁXIMO
AVG -> MÉDIA
COUNT -> CONTAGEM
COUNT DISTINCT -> CONTAGEM DISTINTA

*/

SELECT	SUM(QUANTIDADE) AS QUANTIDADE_TOTAL,
		
		MIN(QUANTIDADE) AS QUANTIDADE_MINIMA,
		
		MAX(QUANTIDADE) AS QUANTIDADE_MAXIMA,

		AVG(QUANTIDADE) AS MEDIA_QUANTIDADE,

		COUNT(*) AS QUANTIDADE_DE_LINHAS,

		COUNT( DISTINCT CLIENTE ) AS QUANTIDADE_DISNTINA_CLIENTES

  FROM VENDAS_ANALITICAS

SELECT	PRODUTO,
		CLIENTE,
		SUM(QUANTIDADE) AS TOTAL_QUANTIDADE,
		COUNT(PRODUTO) AS QUANTIDADE_VENDAS
  FROM	VENDAS_ANALITICAS
 WHERE	PRODUTO = 34902
 GROUP
    BY	PRODUTO, CLIENTE