-- CAST (PADRÃO ANSI)
-- CONVERT

--TRY_CAST

SELECT 'A' + CAST(1 AS VARCHAR(1))


SELECT	PRODUTO,
		CAST(ROUND(VENDA_LIQUIDA / QUANTIDADE, 2) AS NUMERIC(9,2)) AS VALOR_UNITARIO
  FROM	VENDAS_ANALITICAS
 ORDER
    BY VALOR_UNITARIO DESC

SELECT	ENTIDADE,
		CAST(DATA_CADASTRO AS DATE) AS CAST_DATA,
	  --CONVERT(DATE, DATA_CADASTRO) AS CONVERT_DATA
	    CONVERT(VARCHAR, DATA_CADASTRO, 103) AS CONVERT_STR_DATA
  FROM	ENTIDADES
 ORDER
    BY	DATA_CADASTRO

SELECT TRY_CAST('ABC' AS INT)