-- JOIN 
-- INNER JOIN 

SELECT	A.VENDEDOR,
		B.NOME,
		SUM (A.QUANTIDADE) AS QUANTIDADE
  FROM	VENDAS_ANALITICAS A
  INNER JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
 WHERE A.VENDEDOR IN(1,2,3,20)
 GROUP BY A.VENDEDOR, B.NOME
 ORDER BY A.VENDEDOR


SELECT	A.PRODUTO,
		A.DESCRICAO,
		A.FAMILIA_PRODUTO,
		B.DESCRICAO
  FROM	PRODUTOS A
  JOIN	FAMILIAS_PRODUTOS B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO


SELECT	C.DESCRICAO AS FAMILIA,
		SUM(A.QUANTIDADE)
  FROM	VENDAS_ANALITICAS A
  JOIN	PRODUTOS		  B ON A.PRODUTO		 = B.PRODUTO
  JOIN	FAMILIAS_PRODUTOS C ON B.FAMILIA_PRODUTO = C.FAMILIA_PRODUTO
 GROUP
    BY C.DESCRICAO

SELECT	B.MARCA AS CODIGO_MARCA,
		C.DESCRICAO AS DESCRICAO_MARCA,
		SUM(A.VENDA_LIQUIDA) AS TOTAL_VENDA
  FROM	VENDAS_ANALITICAS A
  JOIN	PRODUTOS		  B ON A.PRODUTO = B.PRODUTO
  JOIN	MARCAS			  C ON B.MARCA   = C.MARCA
 GROUP
    BY	B.MARCA,
		C.DESCRICAO
 ORDER
    BY	B.MARCA