-- LEFT JOIN
-- LEFT OUTER JOIN

SELECT	A.PRODUTO,
		A.DESCRICAO,
		A.FAMILIA_PRODUTO,
		COALESCE( B.DESCRICAO, 'NÃO ENCONTRADO') AS DESCRICAO
  FROM	PRODUTOS A
  LEFT JOIN	FAMILIAS_PRODUTOS B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO

SELECT	COUNT(*)
  FROM	PRODUTOS A
--LEFT 
  JOIN	GRUPOS_PRODUTOS B ON A.GRUPO_PRODUTO = B.GRUPO_PRODUTO


SELECT	COUNT(*)
  FROM	PRODUTOS A
--LEFT
  JOIN	FAMILIAS_PRODUTOS B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO


SELECT	COALESCE( C.DESCRICAO, 'NÃO INFORMADO') AS FAMILIA,
		SUM(A.QUANTIDADE)
  FROM	VENDAS_ANALITICAS A
  JOIN	PRODUTOS		  B ON A.PRODUTO		 = B.PRODUTO
  LEFT
  JOIN	FAMILIAS_PRODUTOS C ON B.FAMILIA_PRODUTO = C.FAMILIA_PRODUTO
 GROUP
    BY C.DESCRICAO


SELECT	A.FABRICANTE AS CODIGO_FABRICANTE,
		COALESCE(C.NOME, 'NÃO INFORMADO') AS NOME_FABRICANTE,
		COUNT(DISTINCT A.PRODUTO) AS QUANTIDADE_PRODUTOS,
		AVG(B.VENDA_LIQUIDA) AS MEDIA_VENDAS
  FROM	PRODUTOS A
  LEFT
  JOIN	VENDAS_ANALITICAS B ON A.PRODUTO    = B.PRODUTO
  LEFT
  JOIN	PESSOAS_JURIDICAS C ON A.FABRICANTE = C.ENTIDADE
 GROUP
    BY  A.FABRICANTE,
		C.NOME
 ORDER
    BY	MEDIA_VENDAS DESC
