-- RIGHT JOIN
-- RIGHT OUTER JOIN

SELECT	B.FABRICANTE AS CODIGO_FABRICANTE,
		COALESCE(C.NOME, 'NÃO INFORMADO') AS NOME_FABRICANTE,
		COUNT(DISTINCT B.PRODUTO) AS QUANTIDADE_PRODUTOS,
		AVG(A.VENDA_LIQUIDA) AS MEDIA_VENDAS
  FROM	VENDAS_ANALITICAS A
 RIGHT
  JOIN	PRODUTOS          B ON A.PRODUTO    = B.PRODUTO
  LEFT
  JOIN	PESSOAS_JURIDICAS C ON B.FABRICANTE = C.ENTIDADE
 GROUP
    BY  B.FABRICANTE,
		C.NOME
 ORDER
    BY	MEDIA_VENDAS DESC
	