-- FUNÇÕES DE CONJUNTO

/*
	UNION ALL - UNE DADOS DE DUAS CONSULTAS
	UNION - UNE DADOS DISTINTOS

	-	TODAS AS CONSULTAS DEVEM TER O MESMO NÚMERO DE COLUNAS
	-	TODOS OS TIPOS DE DADOS DEVEM SER COMPATÍVEIS ENTRE COLUNAS
	-	OS ALIAS DA CONSULTA FICAM NO PRIMEIRO COMANDO SELECT
	-	O ORDER BY FICA SEMPRE NO ÚLTIMO COMANDO SELECT

*/

/*		UNION ALL

SELECT	'PESSOA FISICA'		AS TIPO,
		ENTIDADE			AS COD_CLIENTE,
		NOME				AS RAZAO_SOCIAL,
		INSCRICAO_ESTADUAL	AS CPF_CNPJ,
		DATA_CADASTRO
  FROM	PESSOAS_FISICAS

UNION ALL

SELECT	'PESSOA JURIDICA',
		ENTIDADE,
		NOME,
		INSCRICAO_ESTADUAL,
		DATA_CADASTRO
  FROM	PESSOAS_JURIDICAS

UNION ALL

SELECT	'ENTIDADES',
		ENTIDADE,
		NOME,
		INSCRICAO_ESTADUAL,
		DATA_CADASTRO
  FROM	ENTIDADES
 ORDER
	BY	COD_CLIENTE
*/

SELECT	B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL, SUM( A.VALOR ) AS VALOR_RECEBER, 0.00 AS VALOR_PAGAR
  FROM	TITULOS_RECEBER A
  JOIN	ENTIDADES		B ON A.ENTIDADE =  B.ENTIDADE
 GROUP
    BY	B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

UNION ALL

SELECT	B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL, 0.00, SUM( A.VALOR )
  FROM	TITULOS_PAGAR A
  JOIN	ENTIDADES		B ON A.ENTIDADE =  B.ENTIDADE
 GROUP
    BY	B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL
 ORDER
    BY	B.ENTIDADE



SELECT	ENTIDADE			AS COD_CLIENTE,
		NOME				AS RAZAO_SOCIAL,
		INSCRICAO_ESTADUAL	AS CPF_CNPJ,
		DATA_CADASTRO
  FROM	PESSOAS_FISICAS

UNION

SELECT	ENTIDADE,
		NOME,
		INSCRICAO_ESTADUAL,
		DATA_CADASTRO
  FROM	PESSOAS_JURIDICAS

UNION

SELECT	ENTIDADE,
		NOME,
		INSCRICAO_ESTADUAL,
		DATA_CADASTRO
  FROM	ENTIDADES
 ORDER
	BY	COD_CLIENTE