-- FUNÇÕES DE CONJUNTO

/*
	EXCEPT - RETORNA REGISTROS DA CONSULTA A QUE NÃO SE ENCONTRAM NA CONSULTA B
	INTERSECT - RETORNA REGISTROS DA CONSULTA A EM COMUM COM A CONSULTA B
*/

SELECT	B.ENTIDADE,
		B.NOME,
		B.INSCRICAO_FEDERAL
  FROM	TITULOS_PAGAR A
  JOIN	ENTIDADES	  B ON A.ENTIDADE = B.ENTIDADE
 GROUP
    BY	B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

EXCEPT

SELECT	B.ENTIDADE,
		B.NOME,
		B.INSCRICAO_FEDERAL
  FROM	TITULOS_RECEBER A
  JOIN	ENTIDADES	    B ON A.ENTIDADE = B.ENTIDADE
 GROUP
    BY	B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL



SELECT	B.ENTIDADE,
		B.NOME,
		B.INSCRICAO_FEDERAL
  FROM	TITULOS_PAGAR A
  JOIN	ENTIDADES	  B ON A.ENTIDADE = B.ENTIDADE
 GROUP
    BY	B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

INTERSECT

SELECT	B.ENTIDADE,
		B.NOME,
		B.INSCRICAO_FEDERAL
  FROM	TITULOS_RECEBER A
  JOIN	ENTIDADES	    B ON A.ENTIDADE = B.ENTIDADE
 GROUP
    BY	B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL