--RECUPERE O TOTAL DE VENDAS E TOTAL NO ESTOQUE DE CADA PRODUTO 
--> VENDAS ESTÁ NA TABELA VENDAS ANALÍTICAS 
--> ESTOQUE ESTÁ NA TABELA DE ESTOQUE_LANÇAMENTOS 
--> DESCRICAO DO PRODUTO ESTÁ NA TABELA DE PRODUTOS 
--> CRIE UMA COLUNA VIRTUAL ONDE DIVIDA O ESTOQUE EM 3 CATEGORIAS 
	--ABAIXO DE 50 UNIDADES 
	--ENTRE 50 E 1000 UNIDADES 
	--ACIMA DE 1000 UNIDADES 
--> A CONSULTA DEVERÁ RETORNAR OS SEGUINTES CAMPOS 
	--PRODUTO 
	--DESCRICAO 
	--UNIDADES VENDIDAS 
	--UNIDADES EM ESTOQUE 
	--SITUACAO DO ESTOQUE (COLUNA VIRTUAL SOLICITADA) 
--> REALIZE A CONSULTA UTILIZANDO SUBQUERY E DEPOIS REALIZE A MESMA CONSULTA UTILIZANDO TABELAS TEMPORÁRIAS


--SUBQUERY
SELECT	A.PRODUTO,
		A.DESCRICAO,
		COALESCE(CAST(B.UNIDADES_VENDIDAS AS INT),0) AS UNIDADES_VENDIDAS,
		COALESCE(CAST(C.UNIDADES_ESTOQUE AS INT),0) AS UNIDADES_ESTOQUE,
		CASE WHEN C.UNIDADES_ESTOQUE < 50
			 THEN 'ABAIXO DE 50 UNIDADES'
			 WHEN C.UNIDADES_ESTOQUE BETWEEN 50 AND 1000
			 THEN 'ENTRE 50 E 1000 UNIDADES'
			 WHEN C.UNIDADES_ESTOQUE > 1000 
			 THEN 'ACIMA DE 1000 UNIDADES'
			 ELSE 'SEM ENTRADA DE ESTOQUE'
		END AS SITUACAO_ESTOQUE
  FROM	PRODUTOS A
  LEFT
  JOIN	(
		SELECT	PRODUTO,
				SUM(QUANTIDADE) AS UNIDADES_VENDIDAS
		  FROM	VENDAS_ANALITICAS
		 GROUP
			BY	PRODUTO
		) B ON A.PRODUTO = B.PRODUTO
  LEFT
  JOIN	(
		SELECT	PRODUTO,
				SUM(ESTOQUE_ENTRADA) - SUM(ESTOQUE_SAIDA) AS UNIDADES_ESTOQUE
		  FROM	ESTOQUE_LANCAMENTOS
		 GROUP
			BY	PRODUTO
		) C ON A.PRODUTO = C.PRODUTO
--------------------------------------------------------------------------------------------------
--TABELAS TEMPORÁRIAS

SELECT	PRODUTO,
		SUM(QUANTIDADE) AS UNIDADES_VENDIDAS
  INTO	#UNIDADES_VENDIDAS_PRODUTO
  FROM	VENDAS_ANALITICAS
 GROUP
	BY	PRODUTO

SELECT	PRODUTO,
		SUM(ESTOQUE_ENTRADA) - SUM(ESTOQUE_SAIDA) AS UNIDADES_ESTOQUE
  INTO	#UNIDADES_ESTOQUE_PRODUTO
  FROM	ESTOQUE_LANCAMENTOS
 GROUP
	BY	PRODUTO
	
SELECT	A.PRODUTO,
		A.DESCRICAO,
		COALESCE(CAST(B.UNIDADES_VENDIDAS AS INT),0) AS UNIDADES_VENDIDAS,
		COALESCE(CAST(C.UNIDADES_ESTOQUE AS INT),0) AS UNIDADES_ESTOQUE,
		CASE WHEN C.UNIDADES_ESTOQUE < 50
			 THEN 'ABAIXO DE 50 UNIDADES'
			 WHEN C.UNIDADES_ESTOQUE BETWEEN 50 AND 1000
			 THEN 'ENTRE 50 E 1000 UNIDADES'
			 WHEN C.UNIDADES_ESTOQUE > 1000 
			 THEN 'ACIMA DE 1000 UNIDADES'
			 ELSE 'SEM ENTRADA DE ESTOQUE'
		END AS SITUACAO_ESTOQUE
  FROM	PRODUTOS A
  LEFT
  JOIN	#UNIDADES_VENDIDAS_PRODUTO B ON A.PRODUTO = B.PRODUTO
  LEFT
  JOIN	#UNIDADES_ESTOQUE_PRODUTO C ON A.PRODUTO = C.PRODUTO

  DROP TABLE #UNIDADES_ESTOQUE_PRODUTO
  DROP TABLE #UNIDADES_VENDIDAS_PRODUTO