-- INSERT SELECT

BEGIN TRANSACTION
-- BEGIN TRAN

-- ROLLBACK
-- COMMIT

INSERT INTO VENDEDORES 
( NOME,
  ENTIDADE,
  EMPRESA_USUARIA,
  DESCONTO_MAXIMO_PMC )

SELECT NOME,
       ENTIDADE,
	   1 AS EMPRESA_USUARIA,
	   CASE WHEN YEAR( DATA_CADASTRO ) <= 2014
			THEN 10.00
			WHEN YEAR( DATA_CADASTRO ) = 2015
			THEN 5.00
			ELSE 0.00
		END AS DESCONTO_MAXIMO_PMC
  FROM ENTIDADES
 WHERE ENTIDADE BETWEEN 1004 AND 1050

--SELECT * FROM VENDEDORES WITH(NOLOCK)