-- UPDATE

SELECT DESCONTO_MAXIMO_PMC, *
  FROM VENDEDORES
 WHERE VENDEDOR IN ( 1, 2 )

BEGIN TRAN

UPDATE VENDEDORES
   SET DESCONTO_MAXIMO_PMC = 100
 WHERE VENDEDOR IN ( 1, 2 )

BEGIN TRAN

UPDATE VENDEDORES
   SET DESCONTO_MAXIMO_PMC = 0
  FROM VENDEDORES
 WHERE VENDEDOR IN ( 1, 2 )

--COMMIT
--ROLLBACK


SELECT A.CEP,
	   B.CEP,
	   A.ENDERECO AS ENDERECO_ANTIGO,
	   B.ENDERECO AS NOVO_ENDERECO,
	   A.CIDADE AS CIDADE_ANTIGA,
	   B.CIDADE AS NOVA_CIDADE
  FROM ENDERECOS A 
  JOIN CEP		 B ON A.CEP = B.CEP
 WHERE A.ENDERECO <> B.ENDERECO
   AND B.ENDERECO <> ''

BEGIN TRAN
UPDATE ENDERECOS
   SET ENDERECO = B.ENDERECO,
       CIDADE = B.CIDADE
  FROM ENDERECOS A 
  JOIN CEP		 B ON A.CEP = B.CEP
 WHERE A.ENDERECO <> B.ENDERECO
   AND B.ENDERECO <> ''

--COMMIT