/*
-- SINTAXE:

MERGE TABELA_DESTINO D
USING FONTE_DADOS    O ON D.CAMPO_RELACIONAL = O.CAMPO_RELACIONAL

1. WHEN MATCHED THEN
		UPDATED SET D.CAMPO_RELACIONAL = O.CAMPO_RELACIONAL
2. WHEN NOT MATCHED BY TARGET THEN
		INSERT ( D.CAMPO_RELACIONAL )
		VALUES ( D.CAMPO_RELACIONAL )
3. WHEN NOT MATCHED BY SOURCE DELETE;

*/

IF OBJECT_ID( 'TEMPDB..#ATUALIZACAO' ) IS NOT NULL DROP TABLE #ATUALIZACAO

SELECT ENTIDADE,
	   NOME,
	   NOME_FANTASIA,
	   INSCRICAO_FEDERAL,
	   INSCRICAO_ESTADUAL,
	   GETDATE() AS DATA_HORA_INCLUSAO,
	   COALESCE( ATIVO, 'S' ) AS CADASTRO_ATIVO,
	   CLASSIFICACAO_CLIENTE,
	   DATA_CADASTRO
  INTO #ATUALIZACAO
  FROM ENTIDADES A
 WHERE LEN( A.INSCRICAO_FEDERAL ) = 14

 MERGE PESSOAS_FISICAS D
 USING #ATUALIZACAO    O ON D.ENTIDADE = O.ENTIDADE
  WHEN MATCHED THEN
	   UPDATE SET NOME                  = O.NOME, 
                  NOME_FANTASIA         = O.NOME_FANTASIA,
                  INSCRICAO_FEDERAL     = O.INSCRICAO_FEDERAL,
				  INSCRICAO_ESTADUAL    = O.INSCRICAO_ESTADUAL,
				  CADASTRO_ATIVO        = O.CADASTRO_ATIVO,
                  CLASSIFICACAO_CLIENTE = O.CLASSIFICACAO_CLIENTE

  WHEN NOT MATCHED BY TARGET THEN
	   INSERT(
	   ENTIDADE,
	   NOME,
	   NOME_FANTASIA,
	   INSCRICAO_FEDERAL,
	   INSCRICAO_ESTADUAL,
	   DATA_HORA_INCLUSAO,
	   CADASTRO_ATIVO,
	   CLASSIFICACAO_CLIENTE,
	   DATA_CADASTRO )
	   VALUES(
	   O.ENTIDADE,
	   O.NOME, 
	   O.NOME_FANTASIA,
	   O.INSCRICAO_FEDERAL,
	   O.INSCRICAO_ESTADUAL,
	   O.DATA_HORA_INCLUSAO,
	   O.CADASTRO_ATIVO,
	   O.CLASSIFICACAO_CLIENTE,
	   O.DATA_CADASTRO );

IF OBJECT_ID( 'TEMPDB..#ATUALIZACAO_II' ) IS NOT NULL DROP TABLE #ATUALIZACAO_II

SELECT ENTIDADE,
	   NOME,
	   NOME_FANTASIA,
	   INSCRICAO_FEDERAL,
	   INSCRICAO_ESTADUAL,
	   EMPRESA_NACIONAL,
	   GETDATE() AS DATA_HORA_INCLUSAO,
	   COALESCE( ATIVO, 'S' ) AS CADASTRO_ATIVO,
	   CLASSIFICACAO_CLIENTE,
	   DATA_CADASTRO
  INTO #ATUALIZACAO_II
  FROM ENTIDADES A
 WHERE NOT LEN( A.INSCRICAO_FEDERAL ) = 14

 MERGE PESSOAS_JURIDICAS D
 USING #ATUALIZACAO_II    O ON D.ENTIDADE = O.ENTIDADE
  WHEN MATCHED THEN
	   UPDATE SET NOME                  = O.NOME, 
                  NOME_FANTASIA         = O.NOME_FANTASIA,
                  INSCRICAO_FEDERAL     = O.INSCRICAO_FEDERAL,
				  INSCRICAO_ESTADUAL    = O.INSCRICAO_ESTADUAL,
				  EMPRESA_NACIONAL      = O.EMPRESA_NACIONAL,
				  CADASTRO_ATIVO        = O.CADASTRO_ATIVO,
                  CLASSIFICACAO_CLIENTE = O.CLASSIFICACAO_CLIENTE

  WHEN NOT MATCHED BY TARGET THEN
	   INSERT(
	   ENTIDADE,
	   NOME,
	   NOME_FANTASIA,
	   INSCRICAO_FEDERAL,
	   INSCRICAO_ESTADUAL,
	   EMPRESA_NACIONAL,
	   DATA_HORA_INCLUSAO,
	   CADASTRO_ATIVO,
	   CLASSIFICACAO_CLIENTE,
	   DATA_CADASTRO )
	   VALUES(
	   O.ENTIDADE,
	   O.NOME, 
	   O.NOME_FANTASIA,
	   O.INSCRICAO_FEDERAL,
	   O.INSCRICAO_ESTADUAL,
	   O.EMPRESA_NACIONAL,
	   O.DATA_HORA_INCLUSAO,
	   O.CADASTRO_ATIVO,
	   O.CLASSIFICACAO_CLIENTE,
	   O.DATA_CADASTRO );

