CREATE FUNCTION FN_CAMEL_CASE (@TEXTO VARCHAR(4000))

RETURNS VARCHAR(4000)

AS

BEGIN

	DECLARE @POSICAO        INT = 1
	DECLARE @CHAR           CHAR(1)
	DECLARE @CHAR_ANTERIOR  CHAR(1)
	DECLARE @NOME_FORMATADO VARCHAR(100) = LOWER(@TEXTO)
	
	WHILE @POSICAO <= LEN(@TEXTO)
	BEGIN
		
		SET @CHAR = SUBSTRING(@NOME_FORMATADO, @POSICAO, 1)
	
		SET @CHAR_ANTERIOR = IIF(@POSICAO = 1, ' ', SUBSTRING(@NOME_FORMATADO, @POSICAO - 1, 1))
	
		IF @CHAR_ANTERIOR IN (' ', '-') SET @NOME_FORMATADO = STUFF( @NOME_FORMATADO, @POSICAO, 1, UPPER(@CHAR))
	
		SET @POSICAO = @POSICAO + 1
		
	END
	
RETURN @NOME_FORMATADO

END