/*
OPERADORES ARITIMÉTICOS:
+ = ADIÇÃO
- = SUBTRAÇÃO
* = MULTIPLICAÇÃO
/ = DIVISÃO
% = RESTO

SELECT 10 + 5 AS ADICAO
SELECT 10 - 5 AS SUBTRACAO
SELECT 10 * 5 AS MULTIPLICACAO
SELECT 10 / 5 AS DIVISAO
SELECT 10.0 / 4.0 AS DIVISAO_2
SELECT 10 % 5 AS RESTO
SELECT 10 % 4 AS RESTO_2
*/

SELECT	PRODUTO,
		QUANTIDADE,
		VENDA_BRUTA / QUANTIDADE AS VALOR_UNITARIO,
		VENDA_BRUTA
	FROM VENDAS_ANALITICAS

SELECT	VENDA_BRUTA,
		ICMS_ALIQUOTA,
		VENDA_BRUTA * ICMS_ALIQUOTA / 100					AS	IMPOSTO,
		VENDA_BRUTA - ( VENDA_BRUTA * ICMS_ALIQUOTA / 100)	AS	LUCRO_LIQUIDO
	FROM VENDAS_ANALITICAS
	WHERE VENDA_ANALITICA = 18035