IF OBJECT_ID('TEMPDB..#TEMP_01') IS NOT NULL DROP TABLE #TEMP_01

CREATE TABLE #TEMP_01 ( ID INT, NOME VARCHAR(80) )

INSERT INTO #TEMP_01( ID, NOME )

SELECT ENTIDADE, NOME_FANTASIA
  FROM ENTIDADES

SELECT * FROM #TEMP_01

IF OBJECT_ID('TEMPDB..#TEMP_02') IS NOT NULL DROP TABLE #TEMP_02

SELECT ENTIDADE, NOME_FANTASIA
  INTO #TEMP_02
  FROM ENTIDADES

  SELECT * FROM #TEMP_02