WITH UNIDADES_VENDIDAS_PRODUTO AS (
SELECT	PRODUTO,
		SUM(QUANTIDADE) AS UNIDADES_VENDIDAS
  FROM	VENDAS_ANALITICAS
 GROUP
	BY	PRODUTO
) , UNIDADES_ESTOQUE_PRODUTO AS (

SELECT	PRODUTO,
		SUM(ESTOQUE_ENTRADA) - SUM(ESTOQUE_SAIDA) AS UNIDADES_ESTOQUE
  FROM	ESTOQUE_LANCAMENTOS
 GROUP
	BY	PRODUTO
)

SELECT	A.PRODUTO,
		A.DESCRICAO,
		COALESCE(CAST(B.UNIDADES_VENDIDAS AS INT),0) AS UNIDADES_VENDIDAS,
		COALESCE(CAST(C.UNIDADES_ESTOQUE AS INT),0) AS UNIDADES_ESTOQUE,
		CASE WHEN C.UNIDADES_ESTOQUE < 50
			 THEN 'ABAIXO DE 50 UNIDADES'
			 WHEN C.UNIDADES_ESTOQUE BETWEEN 50 AND 1000
			 THEN 'ENTRE 50 E 1000 UNIDADES'
			 WHEN C.UNIDADES_ESTOQUE > 1000 
			 THEN 'ACIMA DE 1000 UNIDADES'
			 ELSE 'SEM ENTRADA DE ESTOQUE'
		END AS SITUACAO_ESTOQUE
  FROM	PRODUTOS A
  LEFT
  JOIN	UNIDADES_VENDIDAS_PRODUTO B ON A.PRODUTO = B.PRODUTO
  LEFT
  JOIN	UNIDADES_ESTOQUE_PRODUTO C ON A.PRODUTO = C.PRODUTO
