DECLARE @MOVIMENTO DATE

SET @MOVIMENTO = '01/01/2021'

SELECT @MOVIMENTO

SET @MOVIMENTO = CAST( GETDATE() AS DATE )

SELECT @MOVIMENTO

----------------------------------------------------------
DECLARE @MOVIMENTO_INI		DATE = '01/01/2020',
		@MOVIMENTO_FIM		DATE = '12/31/2020'
DECLARE @PERCEC_ACRESCIMO	NUMERIC(15,2) = 15.00

--SET @MOVIMENTO_INI = '01/01/2020'
--SET @MOVIMENTO_FIM = '12/31/2020'
--SET @PERCEC_ACRESCIMO = 15.00

SELECT	@MOVIMENTO_INI AS MOVIMENTO_INI,
		@MOVIMENTO_FIM AS MOVIMENTO_FIM,
		TITULO_RECEBER,
		TITULO,
		ENTIDADE,
		VALOR,
		@PERCEC_ACRESCIMO AS PERCENTUAL_JUROS,
		VALOR * ( 1 + ( @PERCEC_ACRESCIMO / 100 ) ) AS VALOR_COM_JUROS
  FROM	TITULOS_RECEBER A
 WHERE	A.MOVIMENTO >= @MOVIMENTO_INI
   AND  A.MOVIMENTO <= @MOVIMENTO_FIM

----------------------------------------------------------
DECLARE @UF_MENOR_VENDA CHAR(2) 

SET @UF_MENOR_VENDA = (

SELECT TOP 1 B.ESTADO
  FROM VENDAS_ANALITICAS A
  JOIN ENDERECOS		 B ON A.CLIENTE = B.ENTIDADE
 GROUP BY B.ESTADO ORDER BY SUM(A.VENDA_LIQUIDA) ASC

 )

SELECT A.ENTIDADE,
	   A.NOME
  FROM ENTIDADES A
  JOIN ENDERECOS B ON A.ENTIDADE = B.ENTIDADE
 WHERE B.ESTADO = @UF_MENOR_VENDA

----------------------------------------------------------

DECLARE @UF_MAIOR_VENDA CHAR(2),
		@VALOR_TOTAL_VENDA NUMERIC(15,2)

SELECT TOP 1 
	  @UF_MAIOR_VENDA = B.ESTADO,
	  @VALOR_TOTAL_VENDA = SUM(A.VENDA_LIQUIDA)
  FROM VENDAS_ANALITICAS A
  JOIN ENDERECOS		 B ON A.CLIENTE = B.ENTIDADE
 GROUP BY B.ESTADO ORDER BY SUM(A.VENDA_LIQUIDA) DESC

SELECT @UF_MAIOR_VENDA, @VALOR_TOTAL_VENDA

----------------------------------------------------------
DECLARE @CLIENTES_ATIVOS TABLE (
	COD_CLIENTE NUMERIC (15),
	NOME_CLIENTE VARCHAR (20),
	TOTAL_VENDIDO MONEY
)

SELECT *
  FROM @CLIENTES_ATIVOS

INSERT INTO @CLIENTES_ATIVOS (
	COD_CLIENTE,
	NOME_CLIENTE,
	TOTAL_VENDIDO
)


SELECT A.ENTIDADE,
	   A.NOME,
	   SUM(B.VENDA_LIQUIDA) AS TOTAL_VENDIDO
  FROM ENTIDADES A
  LEFT
  JOIN VENDAS_ANALITICAS B ON A.ENTIDADE = B.CLIENTE
 WHERE A.ATIVO = 'S'
 GROUP
    BY A.ENTIDADE, A.NOME

SELECT *
  FROM @CLIENTES_ATIVOS