-- FULL JOIN
-- FULL OUTER JOIN

SELECT	COALESCE( A.VENDEDOR, B.VENDEDOR) AS VENDEDOR,
		ISNULL( SUM( A.QUANTIDADE ), 0 ) AS QTD
  FROM	VENDAS_ANALITICAS A
  FULL
  JOIN	VENDEDORES		  B ON A.VENDEDOR = B.VENDEDOR
 GROUP
    BY	COALESCE( A.VENDEDOR, B.VENDEDOR)
 ORDER
    BY	VENDEDOR



SELECT	COALESCE( A.CLIENTE, B.ENTIDADE ) AS COD_CLIENTE,
		B.NOME,
		COALESCE( SUM( A.VENDA_LIQUIDA ), 0 ) AS TOTAL_VENDIDO
  FROM	VENDAS_ANALITICAS A
  FULL
  JOIN	ENTIDADES		  B ON A.CLIENTE = B.ENTIDADE
 GROUP
   BY	COALESCE( A.CLIENTE, B.ENTIDADE ),
		B.NOME
 ORDER
    BY	TOTAL_VENDIDO DESC