-- DELETE

SELECT *
  FROM VENDEDORES

BEGIN TRAN
DELETE VENDEDORES WHERE VENDEDOR = 23

--COMMIT


SELECT *
  FROM VENDEDORES
 WHERE VENDEDOR > 23
   AND DESCONTO_MAXIMO_PMC = 0

BEGIN TRAN
DELETE VENDEDORES
  FROM VENDEDORES
 WHERE VENDEDOR > 23
   AND DESCONTO_MAXIMO_PMC = 0

--COMMIT

SELECT A.*, B.PRODUTO
  FROM MARCAS A
  LEFT
  JOIN PRODUTOS B ON A.MARCA = B.MARCA
 WHERE B.PRODUTO IS NULL

 BEGIN TRAN
--DELETE FROM MARCAS WHERE MARCA IN( 574, 581, 588 )

--DELETE FROM MARCAS
-- WHERE MARCA IN( SELECT A.MARCA
--                   FROM MARCAS A
--                   LEFT
--                   JOIN PRODUTOS B ON A.MARCA = B.MARCA
--                  WHERE B.PRODUTO IS NULL )

--DELETE FROM MARCAS
-- WHERE MARCA NOT IN( SELECT A.MARCA
--                   FROM MARCAS A
--                   JOIN PRODUTOS B ON A.MARCA = B.MARCA )
 
 DELETE MARCAS
   FROM MARCAS A
   LEFT
   JOIN PRODUTOS B ON A.MARCA = B.MARCA
  WHERE B.PRODUTO IS NULL

  --COMMIT

