-- FUNCTION

/* SINTAXE:

CREATE FUNCTION 'NOME FUNÇÃO' ( 'PARAMETROS' TIPAGEM )
RETURNS TIPAGEM 
AS
BEGIN
RETURN ('OPERAÇÃO ESCALAR')
END

*/

--DROP FUNCTION FN_ISBLANK

CREATE FUNCTION FN_ISBLANK( @V1 VARCHAR(50), @V2 VARCHAR(50) )

RETURNS VARCHAR(50)

AS
BEGIN

RETURN ( SELECT CASE WHEN @V1 = '' THEN @V2 ELSE @V1 END )

END

SELECT NOME,
	   COALESCE(DBO.FN_ISBLANK(APELIDO, NOME), NOME) AS APELIDO
  FROM TESTE

-------------------------------------------------------------------------------------------------

 CREATE FUNCTION FN_TIPO_INSCRICAO ( @INSCRICAO_FEDERAL VARCHAR(50) )

 RETURNS CHAR(2)
 AS
 BEGIN

	DECLARE @TIPO_INSCRICAO CHAR(2)

	SET @INSCRICAO_FEDERAL = REPLACE ( REPLACE ( REPLACE ( @INSCRICAO_FEDERAL, '.', '' ), '-', '' ), '/', '')

	SET @TIPO_INSCRICAO =  CASE LEN(@INSCRICAO_FEDERAL)
								WHEN 14
								THEN 'PJ'
								WHEN 11
								THEN 'PF'
								ELSE NULL
							END 
	RETURN @TIPO_INSCRICAO

 END


SELECT ENTIDADE,
       INSCRICAO_FEDERAL,
	DBO.FN_TIPO_INSCRICAO(INSCRICAO_FEDERAL) AS TIPO
 FROM ENTIDADES
WHERE INSCRICAO_FEDERAL IS NOT NULL