--VIEW

CREATE VIEW VW_CLIENTES_CONSOLIDADOS

AS

   SELECT A.ENTIDADE          AS ENTIDADE,
   	      A.NOME              AS NOME,
   	      A.NOME_FANTASIA     AS NOME_FANTASIA,
   	      A.INSCRICAO_FEDERAL AS INSCRICAO_FEDERAL,
   	      B.DESCRICAO         AS CLASSIF_CLIENTE,
   	      C.CIDADE            AS CIDADE, 
   	      D.NOME              AS ESTADO,
   	      C.ESTADO            AS UF
     FROM ENTIDADES               A
LEFT JOIN CLASSIFICACOES_CLIENTES B ON A.CLASSIFICACAO_CLIENTE = B.CLASSIFICACAO_CLIENTE
LEFT JOIN ENDERECOS               C ON A.ENTIDADE              = C.ENTIDADE
LEFT JOIN ESTADOS                 D ON C.ESTADO                = D.ESTADO


SELECT *
  FROM VW_CLIENTES_CONSOLIDADOS