CREATE PROCEDURE USP_FULL_D_CLIENTES

AS

-----------------------------
-- VERIFICA SE SCHEMA EXISTE
-----------------------------

IF OBJECT_ID('PBS_PROCFIT_DW.DBO.D_CLIENTES') IS NULL
BEGIN
	CREATE TABLE D_CLIENTES
	(
	  COD_CLIENTE NUMERIC(15) PRIMARY KEY 
	, NOME VARCHAR(160)
	, NOME_FANTASIA VARCHAR(80)
	, CLASSIFICACAO VARCHAR(160)
	, CIDADE VARCHAR(80)
	, ESTADO VARCHAR(80)
	, UF CHAR(2)
	)
END

----------------
-- FAZENDO MERGE
----------------

MERGE PBS_PROCFIT_DW.DBO.D_CLIENTES D
USING PBS_PROCFIT_ST.DBO.VW_D_CLIENTES O ON D.COD_CLIENTE = O.COD_CLIENTE

-- QUANDO COINCIDIR
WHEN MATCHED THEN UPDATE
SET NOME          = O.NOME           
  , NOME_FANTASIA = O.NOME_FANTASIA	
  , CLASSIFICACAO = O.CLASSIFICACAO_CLIENTE
  , CIDADE		  = O.CIDADE		
  , ESTADO		  = O.ESTADO		
  , UF			  = O.UF			

-- QUANDO NÃO COINCIDIR NO DESTINO
WHEN NOT MATCHED BY TARGET THEN INSERT
( COD_CLIENTE
, NOME         
, NOME_FANTASIA
, CLASSIFICACAO
, CIDADE				
, ESTADO				
, UF			
)

VALUES
( O.COD_CLIENTE
, O.NOME         
, O.NOME_FANTASIA
, O.CLASSIFICACAO_CLIENTE
, O.CIDADE				
, O.ESTADO				
, O.UF			
);
