CREATE PROCEDURE USP_CARGA_F_VENDAS( @INCRIMENTAL BIT )

AS

-----------------------------
-- VERIFICA SE SCHEMA EXISTE
-----------------------------

IF OBJECT_ID('PBS_PROCFIT_DW.DBO.F_VENDAS') IS NULL
BEGIN
	CREATE TABLE F_VENDAS
	(
	  N_DOC NUMERIC(9)
    , COD_EMPRESA NUMERIC(15) REFERENCES D_EMPRESAS ( COD_EMPRESA )
    , COD_CLIENTE NUMERIC(15) REFERENCES D_CLIENTES ( COD_CLIENTE )
    , COD_VENDEDOR NUMERIC(15) REFERENCES D_VENDEDORES ( COD_VENDEDOR )
    , MOVIMENTO DATE
    , COD_PRODUTO NUMERIC(15) REFERENCES D_PRODUTOS ( COD_PRODUTO )
    , QUANTIDADE INT
    , VENDA_BRUTA MONEY
    , DESCONTO_TOTAL MONEY
    , VENDA_LIQUIDA MONEY
	)
END

----------------
-- LIMPA TABELA
----------------
IF @INCRIMENTAL = 0 TRUNCATE TABLE PBS_PROCFIT_DW.DBO.F_VENDAS

-----------------
-- POPULA TABELA
-----------------

INSERT INTO F_VENDAS

SELECT *
  FROM PBS_PROCFIT_ST.DBO.VW_F_VENDAS

