CREATE PROCEDURE USP_ST_CARGA_PRODUTOS

AS

-----------------------------
-- VERIFICA SE SCHEMA EXISTE
-----------------------------

IF OBJECT_ID('PBS_PROCFIT_ST.DBO.ST_PRODUTOS') IS NULL

BEGIN

	CREATE TABLE PBS_PROCFIT_ST.DBO.ST_PRODUTOS
	 (
       COD_PRODUTO         NUMERIC(15)
     , DESCRICAO           VARCHAR(100)
   	 , DESCRICAO_REDUZIDA  VARCHAR(60)
   	 , FAMILIA             VARCHAR(80)
   	 , SECAO               VARCHAR(80)
   	 , GRUPO               VARCHAR(80)
   	 , SUB_GRUPO           VARCHAR(80)
   	 , MARCA               VARCHAR(80)
	 )
	
END

---------------
-- LIMPA STAGE
---------------

TRUNCATE TABLE PBS_PROCFIT_ST.DBO.ST_PRODUTOS


---------------------
-- POPULA STAGE AREA
---------------------

INSERT INTO PBS_PROCFIT_ST.DBO.ST_PRODUTOS

   SELECT A.PRODUTO
        , A.DESCRICAO
   	    , A.DESCRICAO_REDUZIDA
   	    , B.DESCRICAO AS FAMILIA
   	    , C.DESCRICAO AS SECAO
   	    , D.DESCRICAO AS GRUPO
   	    , E.DESCRICAO AS SUBGRUPO
   	    , F.DESCRICAO AS MARCA
     FROM PBS_PROCFIT_DADOS.DBO.PRODUTOS A
LEFT JOIN PBS_PROCFIT_DADOS.DBO.FAMILIAS_PRODUTOS B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO
     JOIN PBS_PROCFIT_DADOS.DBO.SECOES_PRODUTOS C ON A.SECAO_PRODUTO = C.SECAO_PRODUTO
	 JOIN PBS_PROCFIT_DADOS.DBO.GRUPOS_PRODUTOS D ON A.GRUPO_PRODUTO = D.GRUPO_PRODUTO
     JOIN PBS_PROCFIT_DADOS.DBO.SUBGRUPOS_PRODUTOS E ON A.SUBGRUPO_PRODUTO = E.SUBGRUPO_PRODUTO
LEFT JOIN PBS_PROCFIT_DADOS.DBO.MARCAS F ON A.MARCA = F.MARCA