CREATE PROCEDURE USP_FULL_D_PRODUTOS

AS

-----------------------------
-- VERIFICA SE SCHEMA EXISTE
-----------------------------

IF OBJECT_ID('PBS_PROCFIT_DW.DBO.D_PRODUTOS') IS NULL
BEGIN
	CREATE TABLE D_PRODUTOS
	(
	  COD_PRODUTO NUMERIC(15) PRIMARY KEY
	, DESCRICAO VARCHAR(160)
	, DESCRICAO_REDUZIDA VARCHAR(80)
	, FAMILIA VARCHAR(80)
	, SECAO VARCHAR(80)
	, GRUPO VARCHAR(80)
	, SUB_GRUPO VARCHAR(80)
	, MARCA VARCHAR(80)
	)
END

----------------
-- FAZENDO MERGE
----------------

MERGE PBS_PROCFIT_DW.DBO.D_PRODUTOS D
USING PBS_PROCFIT_ST.DBO.VW_D_PRODUTOS O ON D.COD_PRODUTO = O.COD_PRODUTO

-- QUANDO COINCIDIR
WHEN MATCHED THEN UPDATE
SET DESCRICAO          = O.DESCRICAO
  , DESCRICAO_REDUZIDA = O.DESCRICAO_REDUZIDA
  , FAMILIA			   = O.FAMILIA
  , SECAO			   = O.SECAO
  , GRUPO			   = O.GRUPO
  , SUB_GRUPO		   = O.SUB_GRUPO
  , MARCA			   = O.MARCA

-- QUANDO NÃO COINCIDIR NO DESTINO
WHEN NOT MATCHED BY TARGET THEN INSERT
( COD_PRODUTO
, DESCRICAO
, DESCRICAO_REDUZIDA
, FAMILIA
, SECAO
, GRUPO
, SUB_GRUPO
, MARCA
)

VALUES
( O.COD_PRODUTO
, O.DESCRICAO
, O.DESCRICAO_REDUZIDA
, O.FAMILIA
, O.SECAO
, O.GRUPO
, O.SUB_GRUPO
, O.MARCA
);
