/*

--UPPER
--LOWER
--REPLACE
--LEN

--LEFT
--RIGHT
--SUBSTRING

--CHARINDEX
--TRIM
--RTRIM
--LTRIM

*/

SELECT	TOP 100
		UPPER(NOME) AS MAIUSCULAS,
		LOWER(NOME_FANTASIA) AS MINUSCULAS,
		REPLACE(NOME, 'Cliente', '') AS FUNCAO_REPLACE,
		LEN(NOME) AS FUNCAO_LEN,
		LEFT( NOME, 7) AS FUNCAO_LEFT,
		RIGHT( NOME, 4) AS FUNCAO_RIGTH,
		SUBSTRING(NOME, 4,2) AS FUNCAO_SUBSTRING
  FROM ENTIDADES


SELECT	LTRIM(' ESPAÇO A ESQUERDA') AS FUNCAO_LTRIM,
		RTRIM('ESPAÇO A DIREITA ') AS FUNCAO_RTRIM,
		TRIM(' ESPAÇO NOS DOIS ') AS FUNCAO_TRIM



SELECT	CIDADE,
		CHARINDEX(' ', CIDADE) AS FUNCAO_CHARINDEX
  FROM	ENDERECOS