-- CASE WHEN

/*
MENOR OU IGUAL A 0	-> SEM COMISSÃO
ENTRE 1 E 500		-> 1% DE COMISSÃO
ENTRE 501 E 10K		-> 2% DE COMISSÃO
ACIMA DE 10K		-> 3% DE COMISSÃO
*/

SELECT	VENDEDOR,
		VENDA_LIQUIDA,
		CASE WHEN COALESCE(VENDA_LIQUIDA, 0) <= 0
			 THEN 'SEM COMISSÃO'
			 WHEN VENDA_LIQUIDA BETWEEN 1 AND 500
			 THEN '1%'
			 WHEN VENDA_LIQUIDA BETWEEN 501 AND 10000
			 THEN '2%'
			 ELSE '3%'
		END AS COMISSAO,
		CASE WHEN COALESCE(VENDA_LIQUIDA, 0) <= 0
			 THEN 0.00
			 WHEN VENDA_LIQUIDA BETWEEN 1 AND 500
			 THEN VENDA_LIQUIDA * 1 /100
			 WHEN VENDA_LIQUIDA BETWEEN 501 AND 10000
			 THEN VENDA_LIQUIDA * 2 /100
			 ELSE VENDA_LIQUIDA * 3 /100
		END AS VALOR_COMISSAO
  FROM	VENDAS_ANALITICAS


SELECT	VENDEDOR,
		CONCAT(YEAR(MOVIMENTO), RIGHT(MONTH(MOVIMENTO)+100,2)) AS ANO_MES,
		SUM(VENDA_LIQUIDA) AS VENDA_LIQUIDA,
		CASE WHEN SUM(VENDA_LIQUIDA) BETWEEN 1 AND 500
			 THEN '1%'
			 WHEN SUM(VENDA_LIQUIDA) BETWEEN 501 AND 10000
			 THEN '2%'
			 ELSE '3%'
		END AS COMISSAO,
		CASE WHEN SUM(VENDA_LIQUIDA) BETWEEN 1 AND 500
			 THEN SUM(VENDA_LIQUIDA) * 1 / 100
			 WHEN SUM(VENDA_LIQUIDA) BETWEEN 501 AND 10000
			 THEN SUM(VENDA_LIQUIDA) * 2 / 100
			 ELSE SUM(VENDA_LIQUIDA) * 3 / 100
		END AS VALOR_COMISSAO
  FROM	VENDAS_ANALITICAS
 GROUP
    BY VENDEDOR, CONCAT(YEAR(MOVIMENTO), RIGHT(MONTH(MOVIMENTO)+100,2))
HAVING	CASE WHEN SUM(VENDA_LIQUIDA) BETWEEN 1 AND 500
			 THEN SUM(VENDA_LIQUIDA) * 1 / 100
			 WHEN SUM(VENDA_LIQUIDA) BETWEEN 501 AND 10000
			 THEN SUM(VENDA_LIQUIDA) * 2 / 100
			 ELSE SUM(VENDA_LIQUIDA) * 3 / 100
		END > 25000
 ORDER
    BY VALOR_COMISSAO DESC, ANO_MES ASC

SELECT	VENDEDOR,
		QUANTIDADE,
	  --CASE WHEN QUANTIDADE > 0 THEN 'VENDA' ELSE 'DEVOLUÇÃO'END AS TIPO
	    IIF(QUANTIDADE > 0, 'VENDA', 'DEVOLUÇÃO') AS TIPO
  FROM	VENDAS_ANALITICAS


SELECT ENTIDADE,
       INSCRICAO_FEDERAL,
	   REPLACE ( REPLACE ( REPLACE ( INSCRICAO_FEDERAL, '.', '' ), '-', '' ), '/', ''),
	   LEN ( REPLACE ( REPLACE ( REPLACE ( INSCRICAO_FEDERAL, '.', '' ), '-', '' ), '/', '') ),
	  -- CASE WHEN LEN( REPLACE ( REPLACE ( REPLACE ( INSCRICAO_FEDERAL, '.', '' ), '-', '' ), '/', '') ) = 14
	        --THEN 'PJ'
			--WHEN LEN( REPLACE ( REPLACE ( REPLACE ( INSCRICAO_FEDERAL, '.', '' ), '-', '' ), '/', '') ) = 11
			--THEN 'PF'
			--ELSE NULL
	  -- END
	  CASE LEN( REPLACE ( REPLACE ( REPLACE ( INSCRICAO_FEDERAL, '.', '' ), '-', '' ), '/', '') )
	       WHEN 14 THEN 'PJ'
		   WHEN 11 THEN 'PF'
		   ELSE NULL
	  END
  FROM ENTIDADES
 WHERE INSCRICAO_FEDERAL IS NOT NULL